export const CURRENT_TERMS_VERSION = "2026-04-28";
export const TERMS_EFFECTIVE_DATE = "April 28, 2026";
export const TERMS_LAST_UPDATED = "April 28, 2026";

export interface TermsSection {
  id: string;
  heading: string;
  intro?: string;
  body?: string;
  bullets?: string[];
  allCaps?: boolean;
  subsections?: {
    id: string;
    heading: string;
    body?: string;
    bullets?: string[];
    allCaps?: boolean;
    closing?: string;
  }[];
  closing?: string;
}

export const TERMS_INTRO =
  `Please read these Terms and Conditions ("Terms") carefully before using the Man Up God's Way mobile application ("App"), operated by Man Up God's Way Ministry ("Ministry," "we," "us," or "our"). By downloading, installing, accessing, or using the App, you ("User" or "you") confirm that you have read, understood, and agree to be bound by these Terms. If you do not agree with any part of these Terms, do not use the App.`;

export const TERMS_SECTIONS: TermsSection[] = [
  {
    id: "1",
    heading: "1. Purpose and Scope",
    body: "The Man Up God's Way App exists to support the Man Up God's Way ministry by providing spiritual content, community resources, and fitness tools designed to encourage men in their faith, health, and personal development. These Terms govern your use of all features within the App, including but not limited to devotional content, community forums, workout planning, exercise tracking, exercise demonstration media, injury guidance, and calorie and nutrition tools.",
  },
  {
    id: "2",
    heading: "2. Eligibility",
    intro: "By using this App you represent and warrant that:",
    bullets: [
      "You are at least 18 years of age, or at least 13 years of age with verified parental or guardian consent;",
      "You have the legal capacity to enter into a binding agreement;",
      "You will use the App only for lawful purposes consistent with these Terms; and",
      "All registration and profile information you provide is accurate, current, and complete.",
    ],
    closing: "We reserve the right to refuse access to any person at any time at our sole discretion.",
  },
  {
    id: "3",
    heading: "3. Health, Medical, and Fitness Disclaimer",
    intro: "This section is critically important. Please read it in full before using any fitness features.",
    subsections: [
      {
        id: "3.1",
        heading: "3.1 Not Medical Advice",
        body: `The fitness plans, exercise programs, workout recommendations, calorie calculations, nutritional guidance, injury modification suggestions, and all related content ("Fitness Content") are provided for general informational and motivational purposes only. Nothing in the App constitutes medical advice, diagnosis, treatment, or a substitute for professional medical care. You should always consult a qualified physician, licensed healthcare provider, or certified fitness professional before beginning any exercise program, changing your diet, or making any health-related decision — particularly if you have or suspect a medical condition.`,
      },
      {
        id: "3.2",
        heading: "3.2 Assumption of Risk",
        body: "Physical exercise carries inherent risks including, without limitation, muscle strains, joint injuries, cardiovascular events, and in rare cases serious injury or death. By using the fitness features of this App you voluntarily and knowingly assume all such risks. You acknowledge that:",
        bullets: [
          "You are physically capable of engaging in the exercises recommended;",
          "You will stop any activity that causes pain, dizziness, shortness of breath, or any adverse symptom and seek medical attention as needed;",
          "You will obtain physician clearance before beginning if you have any known health condition, injury, or physical limitation; and",
          "The App does not monitor your physical condition in real time and cannot respond to medical emergencies.",
        ],
      },
      {
        id: "3.3",
        heading: "3.3 Injury Flags and Exercise Modifications",
        body: "The injury flagging and exercise modification features within the App are general guidance tools only, not a substitute for professional medical assessment, physical therapy, or rehabilitation advice. Suggested modifications for flagged conditions are based on general principles — individual safety and outcomes will vary. If you have a current injury, chronic condition, or are recovering from surgery or illness, you must obtain medical clearance before using any fitness features. We are not responsible for aggravation of existing conditions or new injuries resulting from use of the injury guidance features.",
      },
      {
        id: "3.4",
        heading: "3.4 AI-Generated and Adaptive Workout Plans",
        body: "Workout plans and adaptive difficulty adjustments generated by the App are produced by automated algorithms. They are not individually created or reviewed by certified personal trainers, exercise physiologists, or medical professionals. Generated plans are starting frameworks — not individually prescribed programs. The Ministry makes no representation that any generated plan is appropriate for your specific health status, fitness level, or goals. You use all generated plans at your own risk.",
      },
      {
        id: "3.5",
        heading: "3.5 Calorie and Nutrition Estimates",
        body: "Calorie targets, BMR estimates, and TDEE calculations provided through the App are generated using standardized formulas (including the Mifflin-St Jeor equation) applied to user-provided inputs. These are estimates and may not reflect your individual metabolic rate. We are not registered dietitians or licensed nutritionists. Do not use these estimates as the sole basis for a medically supervised dietary plan or clinical nutrition program. Consult a registered dietitian or your healthcare provider for personalized nutritional guidance.",
      },
      {
        id: "3.6",
        heading: "3.6 Exercise Demonstration Media",
        body: "Exercise demonstration videos and images within the App are provided to illustrate general exercise form and technique. You are solely responsible for performing all exercises within your physical capabilities and with proper form. If any demonstrated exercise conflicts with guidance from your healthcare provider or trainer, follow your professional's instruction over the App's demonstration.",
      },
    ],
  },
  {
    id: "4",
    heading: "4. User Accounts and Access",
    subsections: [
      {
        id: "4.1",
        heading: "4.1 Account Creation",
        body: "To access certain features of the App you may be required to create an account. You agree to provide accurate and complete information during registration and to keep your account information current. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account.",
      },
      {
        id: "4.2",
        heading: "4.2 Account Security",
        body: "You agree to notify us immediately of any unauthorized use of your account or any security breach at the contact information provided in Section 17. We will not be liable for any loss or damage arising from your failure to maintain account security.",
      },
      {
        id: "4.3",
        heading: "4.3 Account Suspension and Termination",
        body: "We may suspend, restrict, or permanently terminate your account and access to the App at any time, with or without notice, for any reason including violation of these Terms, conduct harmful to the Ministry or other users, or any unlawful activity. Upon termination your right to use the App ceases immediately.",
      },
    ],
  },
  {
    id: "5",
    heading: "5. User Content",
    subsections: [
      {
        id: "5.1",
        heading: "5.1 Ownership",
        body: `You retain ownership of content, data, and material you submit through the App ("User Content"), including personal fitness data, workout logs, progress entries, profile information, and community contributions.`,
      },
      {
        id: "5.2",
        heading: "5.2 License Grant",
        body: "By submitting User Content you grant Man Up God's Way a non-exclusive, royalty-free, worldwide license to store, display, process, and use your User Content solely for the purposes of operating and improving the App and delivering services to you. We will not sell your personal User Content to third parties.",
      },
      {
        id: "5.3",
        heading: "5.3 Prohibited Content",
        body: "You agree not to submit any User Content that:",
        bullets: [
          "Is unlawful, abusive, harassing, defamatory, threatening, or obscene;",
          "Infringes any intellectual property, privacy, or other rights of any party;",
          "Contains viruses, malware, or other harmful code;",
          "Is false, misleading, or deceptive;",
          "Promotes hate speech, discrimination, or violence; or",
          "Is contrary to the values and mission of the Man Up God's Way Ministry.",
        ],
        closing: "We reserve the right to remove any User Content at our sole discretion.",
      },
    ],
  },
  {
    id: "6",
    heading: "6. Health Data and Privacy",
    subsections: [
      {
        id: "6.1",
        heading: "6.1 Collection of Health Information",
        body: "The App collects health and fitness information you voluntarily provide, including age, weight, height, biological sex, activity level, fitness goals, injury history, workout logs, and exercise feedback. This information is used exclusively to generate and adapt your fitness experience within the App.",
      },
      {
        id: "6.2",
        heading: "6.2 Sensitive Health Data",
        body: "We recognize that health and fitness data is sensitive personal information. We are committed to handling your data with care and in compliance with applicable law. We do not sell, rent, or share your individually identifiable health data with third-party advertisers or data brokers.",
      },
      {
        id: "6.3",
        heading: "6.3 Privacy Policy",
        body: "The collection, use, storage, and protection of your personal information is governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the App you consent to the data practices described in our Privacy Policy.",
      },
      {
        id: "6.4",
        heading: "6.4 Data Export and Deletion",
        body: "You may request a copy of your personal data or request deletion of your account and associated data at any time by contacting us at the information provided in Section 17. We will respond to such requests within 30 days.",
      },
    ],
  },
  {
    id: "7",
    heading: "7. Intellectual Property",
    subsections: [
      {
        id: "7.1",
        heading: "7.1 Ministry Content",
        body: "All content within the App that is not User Content — including exercise videos, images, written instructions, devotional content, logos, graphics, audio, software code, workout plan structures, and the overall design of the App — is owned by or licensed to Man Up God's Way Ministry and is protected by United States and international copyright, trademark, and other intellectual property laws.",
      },
      {
        id: "7.2",
        heading: "7.2 Limited License to Users",
        body: "We grant you a limited, non-exclusive, non-transferable, revocable license to access and use the App and its content for your personal, non-commercial use only. This license does not include the right to:",
        bullets: [
          "Copy, reproduce, distribute, or publicly display any App content;",
          "Modify, reverse engineer, or create derivative works;",
          "Use any content for commercial purposes; or",
          "Remove or alter any copyright, trademark, or other proprietary notices.",
        ],
      },
      {
        id: "7.3",
        heading: "7.3 Feedback",
        body: "If you provide suggestions, ideas, or feedback about the App, you grant us a perpetual, irrevocable, royalty-free right to use that feedback for any purpose without compensation or attribution to you.",
      },
    ],
  },
  {
    id: "8",
    heading: "8. Prohibited Conduct",
    intro: "You agree that you will not:",
    bullets: [
      "Use the App for any unlawful, fraudulent, or unauthorized purpose;",
      "Attempt to gain unauthorized access to any part of the App or other user accounts;",
      "Use automated scripts, bots, or scrapers to collect data from the App;",
      "Interfere with or disrupt the App's servers, networks, or infrastructure;",
      "Impersonate any person or entity or misrepresent your affiliation;",
      "Circumvent any security or access control measures;",
      "Use the App in any manner that could damage or overburden its functionality; or",
      "Use the App to transmit unsolicited commercial communications.",
    ],
  },
  {
    id: "9",
    heading: "9. Third-Party Services",
    body: "The App may integrate with or reference third-party services, platforms, or websites. These services are not under our control and we are not responsible for their content, privacy practices, or terms. Any interaction you have with a third-party service is solely between you and that third party. We encourage you to review the terms and privacy policies of any third-party service you access through the App.",
  },
  {
    id: "10",
    heading: "10. Disclaimer of Warranties",
    allCaps: true,
    body: `THE APP AND ALL CONTENT, FEATURES, AND SERVICES ARE PROVIDED ON AN "AS-IS" AND "AS-AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, MAN UP GOD'S WAY MINISTRY EXPRESSLY DISCLAIMS ALL WARRANTIES, INCLUDING:`,
    bullets: [
      "IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT;",
      "ANY WARRANTY THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE;",
      "ANY WARRANTY REGARDING THE ACCURACY OR COMPLETENESS OF ANY FITNESS PLANS, CALORIE CALCULATIONS, EXERCISE INSTRUCTIONS, INJURY GUIDANCE, OR OTHER CONTENT; AND",
      "ANY WARRANTY THAT THE APP WILL MEET YOUR SPECIFIC HEALTH, FITNESS, OR PERSONAL GOALS.",
    ],
    closing: "YOUR USE OF THE APP IS AT YOUR SOLE RISK.",
  },
  {
    id: "11",
    heading: "11. Limitation of Liability",
    allCaps: true,
    body: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL MAN UP GOD'S WAY MINISTRY, ITS OFFICERS, DIRECTORS, EMPLOYEES, VOLUNTEERS, AGENTS, OR PARTNERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING:",
    bullets: [
      "PERSONAL INJURY OR BODILY HARM, INCLUDING DEATH, ARISING FROM USE OF THE FITNESS FEATURES;",
      "AGGRAVATION OF A PRE-EXISTING INJURY OR MEDICAL CONDITION;",
      "LOSS OF DATA, PROFITS, OR GOODWILL;",
      "COSTS OF SUBSTITUTE SERVICES; OR",
      "ANY OTHER INTANGIBLE LOSS,",
    ],
    closing: `ARISING OUT OF OR IN CONNECTION WITH YOUR USE OR INABILITY TO USE THE APP, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

OUR TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO US IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED DOLLARS ($100.00 USD).

SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS OF LIABILITY. IN SUCH JURISDICTIONS OUR LIABILITY IS LIMITED TO THE FULLEST EXTENT PERMITTED BY LAW.`,
  },
  {
    id: "12",
    heading: "12. Indemnification",
    body: "You agree to indemnify, defend, and hold harmless Man Up God's Way Ministry and its officers, directors, employees, volunteers, and agents from and against any claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or connected with: (a) your use of or access to the App; (b) your violation of these Terms; (c) your violation of any applicable law; (d) your User Content; or (e) any personal injury or property damage caused by your actions in connection with the fitness features of the App.",
  },
  {
    id: "13",
    heading: "13. Modifications to the App and Terms",
    body: "We reserve the right to modify, suspend, or discontinue the App or any feature thereof at any time without notice or liability. We also reserve the right to amend these Terms at any time. When we make material changes, we will update the Effective Date and, where practicable, provide notice within the App. Your continued use of the App after any changes constitutes your acceptance of the updated Terms. It is your responsibility to review these Terms periodically.",
  },
  {
    id: "14",
    heading: "14. Termination",
    body: "These Terms are effective until terminated. You may stop using the App at any time. We may terminate or suspend your access immediately, without prior notice or liability, for any reason including breach of these Terms. Upon termination: (a) your right to use the App immediately ceases; and (b) Sections 3, 6, 7, 10, 11, and 12 survive termination indefinitely.",
  },
  {
    id: "15",
    heading: "15. Governing Law and Dispute Resolution",
    subsections: [
      {
        id: "15.1",
        heading: "15.1 Governing Law",
        body: "These Terms are governed by and construed in accordance with the laws of the United States and the state in which Man Up God's Way Ministry is principally located, without regard to conflict of law principles.",
      },
      {
        id: "15.2",
        heading: "15.2 Informal Resolution",
        body: "Before initiating any formal legal proceeding, you agree to first contact us and attempt to resolve any dispute informally by providing written notice of your claim. We will attempt to resolve the dispute within 30 days of receiving your written notice.",
      },
      {
        id: "15.3",
        heading: "15.3 Binding Arbitration",
        body: "If informal resolution fails, any dispute arising out of or relating to these Terms or the App shall be resolved by binding arbitration administered by a recognized arbitration body under its applicable rules, rather than in court, except that either party may seek injunctive or other equitable relief in a court of competent jurisdiction to prevent irreparable harm pending arbitration.",
      },
      {
        id: "15.4",
        heading: "15.4 Class Action Waiver",
        body: "YOU AND MAN UP GOD'S WAY AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING.",
        allCaps: true,
      },
    ],
  },
  {
    id: "16",
    heading: "16. General Provisions",
    subsections: [
      {
        id: "16.1",
        heading: "16.1 Entire Agreement",
        body: "These Terms, together with our Privacy Policy, constitute the entire agreement between you and Man Up God's Way Ministry regarding the App and supersede all prior agreements, representations, and understandings.",
      },
      {
        id: "16.2",
        heading: "16.2 Severability",
        body: "If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall continue in full force and effect.",
      },
      {
        id: "16.3",
        heading: "16.3 No Waiver",
        body: "Our failure to enforce any right or provision of these Terms shall not be considered a waiver of that right or provision.",
      },
      {
        id: "16.4",
        heading: "16.4 Assignment",
        body: "You may not assign or transfer your rights or obligations under these Terms without our prior written consent. We may assign our rights and obligations without restriction.",
      },
      {
        id: "16.5",
        heading: "16.5 Force Majeure",
        body: "We will not be liable for any delay or failure to perform resulting from causes outside our reasonable control, including acts of God, natural disasters, war, terrorism, government action, or Internet service disruption.",
      },
    ],
  },
  {
    id: "17",
    heading: "17. Contact Us",
    body: "If you have questions, concerns, or requests regarding these Terms or your use of the App, please contact us:",
    closing: `Man Up God's Way Ministry\nEmail: info@manupgodsway.org\nWebsite: https://www.manupgodsway.org\nMailing Address: 1729 W 5th St, Byrnes Mill, MO 63025`,
  },
];

export const TERMS_CLOSING =
  `By downloading, installing, or using this App, you acknowledge that you have read these Terms and Conditions in their entirety, that you understand them, and that you agree to be bound by them.`;
